// flow-typed signature: 3a39810598b0af4283bde86db699ed81
// flow-typed version: <<STUB>>/circular-json_v^0.3.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'circular-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'circular-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'circular-json/build/circular-json' {
  declare module.exports: any;
}

declare module 'circular-json/build/circular-json.max' {
  declare module.exports: any;
}

declare module 'circular-json/build/circular-json.node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'circular-json/build/circular-json.js' {
  declare module.exports: $Exports<'circular-json/build/circular-json'>;
}
declare module 'circular-json/build/circular-json.max.js' {
  declare module.exports: $Exports<'circular-json/build/circular-json.max'>;
}
declare module 'circular-json/build/circular-json.node.js' {
  declare module.exports: $Exports<'circular-json/build/circular-json.node'>;
}
