// flow-typed signature: 82e0055a163a373740dd05c2fb584b51
// flow-typed version: <<STUB>>/clean-css-cli_v^4.2.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-css-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-css-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'clean-css-cli/index' {
  declare module.exports: $Exports<'clean-css-cli'>;
}
declare module 'clean-css-cli/index.js' {
  declare module.exports: $Exports<'clean-css-cli'>;
}
