// flow-typed signature: d57c14f523d93c9b486be3a539d7d5c1
// flow-typed version: <<STUB>>/computed-async-mobx_v4.1.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'computed-async-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'computed-async-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'computed-async-mobx/built/interactive-tests/index' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/asyncComputed' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/autorunThrottled' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/deprecatedComputedAsync' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/Getter' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/index' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/mobxShim' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/promisedComputed' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/src/throttledComputed' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/test/asyncComputedRenderTests' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/test/asyncComputedTests' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/test/delay' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/test/deprecatedComputedAsyncTests' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/test/promisedComputedTests' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/test/throttledComputedTests' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/built/test/util' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/fix-coverage' {
  declare module.exports: any;
}

declare module 'computed-async-mobx/interactive-tests/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'computed-async-mobx/built/interactive-tests/index.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/interactive-tests/index'>;
}
declare module 'computed-async-mobx/built/src/asyncComputed.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/asyncComputed'>;
}
declare module 'computed-async-mobx/built/src/autorunThrottled.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/autorunThrottled'>;
}
declare module 'computed-async-mobx/built/src/deprecatedComputedAsync.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/deprecatedComputedAsync'>;
}
declare module 'computed-async-mobx/built/src/Getter.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/Getter'>;
}
declare module 'computed-async-mobx/built/src/index.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/index'>;
}
declare module 'computed-async-mobx/built/src/mobxShim.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/mobxShim'>;
}
declare module 'computed-async-mobx/built/src/promisedComputed.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/promisedComputed'>;
}
declare module 'computed-async-mobx/built/src/throttledComputed.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/src/throttledComputed'>;
}
declare module 'computed-async-mobx/built/test/asyncComputedRenderTests.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/test/asyncComputedRenderTests'>;
}
declare module 'computed-async-mobx/built/test/asyncComputedTests.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/test/asyncComputedTests'>;
}
declare module 'computed-async-mobx/built/test/delay.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/test/delay'>;
}
declare module 'computed-async-mobx/built/test/deprecatedComputedAsyncTests.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/test/deprecatedComputedAsyncTests'>;
}
declare module 'computed-async-mobx/built/test/promisedComputedTests.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/test/promisedComputedTests'>;
}
declare module 'computed-async-mobx/built/test/throttledComputedTests.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/test/throttledComputedTests'>;
}
declare module 'computed-async-mobx/built/test/util.js' {
  declare module.exports: $Exports<'computed-async-mobx/built/test/util'>;
}
declare module 'computed-async-mobx/fix-coverage.js' {
  declare module.exports: $Exports<'computed-async-mobx/fix-coverage'>;
}
declare module 'computed-async-mobx/interactive-tests/webpack.config.js' {
  declare module.exports: $Exports<'computed-async-mobx/interactive-tests/webpack.config'>;
}
