// flow-typed signature: fe7127f717a061d8ab11e089320d2448
// flow-typed version: <<STUB>>/jsoneditor-react_v^1.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsoneditor-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsoneditor-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsoneditor-react/dist/jsoneditor-react.min' {
  declare module.exports: any;
}

declare module 'jsoneditor-react/es/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsoneditor-react/dist/jsoneditor-react.min.js' {
  declare module.exports: $Exports<'jsoneditor-react/dist/jsoneditor-react.min'>;
}
declare module 'jsoneditor-react/es/index.js' {
  declare module.exports: $Exports<'jsoneditor-react/es/index'>;
}
