// flow-typed signature: 3b0c9d2042c6b249817bec961d3303f3
// flow-typed version: <<STUB>>/primereact_v^3.1.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primereact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primereact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'primereact/accordion' {
  declare module.exports: any;
}

declare module 'primereact/autocomplete' {
  declare module.exports: any;
}

declare module 'primereact/breadcrumb' {
  declare module.exports: any;
}

declare module 'primereact/button' {
  declare module.exports: any;
}

declare module 'primereact/calendar' {
  declare module.exports: any;
}

declare module 'primereact/captcha' {
  declare module.exports: any;
}

declare module 'primereact/card' {
  declare module.exports: any;
}

declare module 'primereact/chart' {
  declare module.exports: any;
}

declare module 'primereact/checkbox' {
  declare module.exports: any;
}

declare module 'primereact/chips' {
  declare module.exports: any;
}

declare module 'primereact/colorpicker' {
  declare module.exports: any;
}

declare module 'primereact/column' {
  declare module.exports: any;
}

declare module 'primereact/columngroup' {
  declare module.exports: any;
}

declare module 'primereact/components/accordion/Accordion' {
  declare module.exports: any;
}

declare module 'primereact/components/autocomplete/AutoComplete' {
  declare module.exports: any;
}

declare module 'primereact/components/autocomplete/AutoCompletePanel' {
  declare module.exports: any;
}

declare module 'primereact/components/breadcrumb/BreadCrumb' {
  declare module.exports: any;
}

declare module 'primereact/components/button/Button' {
  declare module.exports: any;
}

declare module 'primereact/components/calendar/Calendar' {
  declare module.exports: any;
}

declare module 'primereact/components/calendar/CalendarPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/captcha/Captcha' {
  declare module.exports: any;
}

declare module 'primereact/components/card/Card' {
  declare module.exports: any;
}

declare module 'primereact/components/chart/Chart' {
  declare module.exports: any;
}

declare module 'primereact/components/checkbox/Checkbox' {
  declare module.exports: any;
}

declare module 'primereact/components/chips/Chips' {
  declare module.exports: any;
}

declare module 'primereact/components/colorpicker/ColorPicker' {
  declare module.exports: any;
}

declare module 'primereact/components/colorpicker/ColorPickerPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/column/Column' {
  declare module.exports: any;
}

declare module 'primereact/components/columngroup/ColumnGroup' {
  declare module.exports: any;
}

declare module 'primereact/components/contextmenu/ContextMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/datascroller/DataScroller' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/BodyCell' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/BodyRow' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/DataTable' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/FooterCell' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/HeaderCell' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/RowCheckbox' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/RowRadioButton' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/ScrollableView' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/TableBody' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/TableFooter' {
  declare module.exports: any;
}

declare module 'primereact/components/datatable/TableHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/dataview/DataView' {
  declare module.exports: any;
}

declare module 'primereact/components/deferredcontent/DeferredContent' {
  declare module.exports: any;
}

declare module 'primereact/components/dialog/Dialog' {
  declare module.exports: any;
}

declare module 'primereact/components/dropdown/Dropdown' {
  declare module.exports: any;
}

declare module 'primereact/components/dropdown/DropdownItem' {
  declare module.exports: any;
}

declare module 'primereact/components/dropdown/DropdownPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/editor/Editor' {
  declare module.exports: any;
}

declare module 'primereact/components/fieldset/Fieldset' {
  declare module.exports: any;
}

declare module 'primereact/components/fileupload/FileUpload' {
  declare module.exports: any;
}

declare module 'primereact/components/fullcalendar/FullCalendar' {
  declare module.exports: any;
}

declare module 'primereact/components/gmap/GMap' {
  declare module.exports: any;
}

declare module 'primereact/components/growl/Growl' {
  declare module.exports: any;
}

declare module 'primereact/components/growl/GrowlMessage' {
  declare module.exports: any;
}

declare module 'primereact/components/inplace/Inplace' {
  declare module.exports: any;
}

declare module 'primereact/components/inputmask/InputMask' {
  declare module.exports: any;
}

declare module 'primereact/components/inputswitch/InputSwitch' {
  declare module.exports: any;
}

declare module 'primereact/components/inputtext/InputText' {
  declare module.exports: any;
}

declare module 'primereact/components/inputtextarea/InputTextarea' {
  declare module.exports: any;
}

declare module 'primereact/components/keyfilter/KeyFilter' {
  declare module.exports: any;
}

declare module 'primereact/components/lightbox/Lightbox' {
  declare module.exports: any;
}

declare module 'primereact/components/listbox/ListBox' {
  declare module.exports: any;
}

declare module 'primereact/components/listbox/ListBoxHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/listbox/ListBoxItem' {
  declare module.exports: any;
}

declare module 'primereact/components/megamenu/MegaMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/menu/Menu' {
  declare module.exports: any;
}

declare module 'primereact/components/menubar/Menubar' {
  declare module.exports: any;
}

declare module 'primereact/components/menubar/MenubarSub' {
  declare module.exports: any;
}

declare module 'primereact/components/message/Message' {
  declare module.exports: any;
}

declare module 'primereact/components/messages/Messages' {
  declare module.exports: any;
}

declare module 'primereact/components/messages/UIMessage' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelect' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelectHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelectItem' {
  declare module.exports: any;
}

declare module 'primereact/components/multiselect/MultiSelectPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/orderlist/OrderList' {
  declare module.exports: any;
}

declare module 'primereact/components/orderlist/OrderListControls' {
  declare module.exports: any;
}

declare module 'primereact/components/orderlist/OrderListSubList' {
  declare module.exports: any;
}

declare module 'primereact/components/organizationchart/OrganizationChart' {
  declare module.exports: any;
}

declare module 'primereact/components/overlaypanel/OverlayPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/CurrentPageReport' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/FirstPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/LastPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/NextPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/PageLinks' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/Paginator' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/PrevPageLink' {
  declare module.exports: any;
}

declare module 'primereact/components/paginator/RowsPerPageDropdown' {
  declare module.exports: any;
}

declare module 'primereact/components/panel/Panel' {
  declare module.exports: any;
}

declare module 'primereact/components/panelmenu/PanelMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/password/Password' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickList' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListControls' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListItem' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListSubList' {
  declare module.exports: any;
}

declare module 'primereact/components/picklist/PickListTransferControls' {
  declare module.exports: any;
}

declare module 'primereact/components/progressbar/ProgressBar' {
  declare module.exports: any;
}

declare module 'primereact/components/progressspinner/ProgressSpinner' {
  declare module.exports: any;
}

declare module 'primereact/components/radiobutton/RadioButton' {
  declare module.exports: any;
}

declare module 'primereact/components/rating/Rating' {
  declare module.exports: any;
}

declare module 'primereact/components/row/Row' {
  declare module.exports: any;
}

declare module 'primereact/components/scrollpanel/ScrollPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/selectbutton/SelectButton' {
  declare module.exports: any;
}

declare module 'primereact/components/selectbutton/SelectButtonItem' {
  declare module.exports: any;
}

declare module 'primereact/components/sidebar/Sidebar' {
  declare module.exports: any;
}

declare module 'primereact/components/slidemenu/SlideMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/slider/Slider' {
  declare module.exports: any;
}

declare module 'primereact/components/spinner/Spinner' {
  declare module.exports: any;
}

declare module 'primereact/components/splitbutton/SplitButton' {
  declare module.exports: any;
}

declare module 'primereact/components/splitbutton/SplitButtonItem' {
  declare module.exports: any;
}

declare module 'primereact/components/splitbutton/SplitButtonPanel' {
  declare module.exports: any;
}

declare module 'primereact/components/steps/Steps' {
  declare module.exports: any;
}

declare module 'primereact/components/tabmenu/TabMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/tabview/TabView' {
  declare module.exports: any;
}

declare module 'primereact/components/tieredmenu/TieredMenu' {
  declare module.exports: any;
}

declare module 'primereact/components/tieredmenu/TieredMenuSub' {
  declare module.exports: any;
}

declare module 'primereact/components/togglebutton/ToggleButton' {
  declare module.exports: any;
}

declare module 'primereact/components/toolbar/Toolbar' {
  declare module.exports: any;
}

declare module 'primereact/components/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'primereact/components/tree/Tree' {
  declare module.exports: any;
}

declare module 'primereact/components/tree/UITreeNode' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTable' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableBody' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableBodyCell' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableFooter' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableHeader' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableNode' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableRow' {
  declare module.exports: any;
}

declare module 'primereact/components/treetable/TreeTableScrollableView' {
  declare module.exports: any;
}

declare module 'primereact/components/tristatecheckbox/TriStateCheckbox' {
  declare module.exports: any;
}

declare module 'primereact/components/utils/DomHandler' {
  declare module.exports: any;
}

declare module 'primereact/components/utils/ObjectUtils' {
  declare module.exports: any;
}

declare module 'primereact/components/utils/UniqueComponentId' {
  declare module.exports: any;
}

declare module 'primereact/contextmenu' {
  declare module.exports: any;
}

declare module 'primereact/datascroller' {
  declare module.exports: any;
}

declare module 'primereact/datatable' {
  declare module.exports: any;
}

declare module 'primereact/dataview' {
  declare module.exports: any;
}

declare module 'primereact/deferredcontent' {
  declare module.exports: any;
}

declare module 'primereact/dialog' {
  declare module.exports: any;
}

declare module 'primereact/dropdown' {
  declare module.exports: any;
}

declare module 'primereact/editor' {
  declare module.exports: any;
}

declare module 'primereact/fieldset' {
  declare module.exports: any;
}

declare module 'primereact/fileupload' {
  declare module.exports: any;
}

declare module 'primereact/fullcalendar' {
  declare module.exports: any;
}

declare module 'primereact/gmap' {
  declare module.exports: any;
}

declare module 'primereact/growl' {
  declare module.exports: any;
}

declare module 'primereact/inputmask' {
  declare module.exports: any;
}

declare module 'primereact/inputswitch' {
  declare module.exports: any;
}

declare module 'primereact/inputtext' {
  declare module.exports: any;
}

declare module 'primereact/inputtextarea' {
  declare module.exports: any;
}

declare module 'primereact/lightbox' {
  declare module.exports: any;
}

declare module 'primereact/listbox' {
  declare module.exports: any;
}

declare module 'primereact/megamenu' {
  declare module.exports: any;
}

declare module 'primereact/menu' {
  declare module.exports: any;
}

declare module 'primereact/menubar' {
  declare module.exports: any;
}

declare module 'primereact/message' {
  declare module.exports: any;
}

declare module 'primereact/messages' {
  declare module.exports: any;
}

declare module 'primereact/multiselect' {
  declare module.exports: any;
}

declare module 'primereact/orderlist' {
  declare module.exports: any;
}

declare module 'primereact/organizationchart' {
  declare module.exports: any;
}

declare module 'primereact/overlaypanel' {
  declare module.exports: any;
}

declare module 'primereact/paginator' {
  declare module.exports: any;
}

declare module 'primereact/panel' {
  declare module.exports: any;
}

declare module 'primereact/panelmenu' {
  declare module.exports: any;
}

declare module 'primereact/password' {
  declare module.exports: any;
}

declare module 'primereact/picklist' {
  declare module.exports: any;
}

declare module 'primereact/progressbar' {
  declare module.exports: any;
}

declare module 'primereact/progressspinner' {
  declare module.exports: any;
}

declare module 'primereact/radiobutton' {
  declare module.exports: any;
}

declare module 'primereact/rating' {
  declare module.exports: any;
}

declare module 'primereact/row' {
  declare module.exports: any;
}

declare module 'primereact/scrollpanel' {
  declare module.exports: any;
}

declare module 'primereact/selectbutton' {
  declare module.exports: any;
}

declare module 'primereact/sidebar' {
  declare module.exports: any;
}

declare module 'primereact/slidemenu' {
  declare module.exports: any;
}

declare module 'primereact/slider' {
  declare module.exports: any;
}

declare module 'primereact/spinner' {
  declare module.exports: any;
}

declare module 'primereact/splitbutton' {
  declare module.exports: any;
}

declare module 'primereact/steps' {
  declare module.exports: any;
}

declare module 'primereact/tabmenu' {
  declare module.exports: any;
}

declare module 'primereact/tabview' {
  declare module.exports: any;
}

declare module 'primereact/tieredmenu' {
  declare module.exports: any;
}

declare module 'primereact/togglebutton' {
  declare module.exports: any;
}

declare module 'primereact/toolbar' {
  declare module.exports: any;
}

declare module 'primereact/tooltip' {
  declare module.exports: any;
}

declare module 'primereact/tree' {
  declare module.exports: any;
}

declare module 'primereact/treetable' {
  declare module.exports: any;
}

declare module 'primereact/tristatecheckbox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'primereact/accordion.js' {
  declare module.exports: $Exports<'primereact/accordion'>;
}
declare module 'primereact/autocomplete.js' {
  declare module.exports: $Exports<'primereact/autocomplete'>;
}
declare module 'primereact/breadcrumb.js' {
  declare module.exports: $Exports<'primereact/breadcrumb'>;
}
declare module 'primereact/button.js' {
  declare module.exports: $Exports<'primereact/button'>;
}
declare module 'primereact/calendar.js' {
  declare module.exports: $Exports<'primereact/calendar'>;
}
declare module 'primereact/captcha.js' {
  declare module.exports: $Exports<'primereact/captcha'>;
}
declare module 'primereact/card.js' {
  declare module.exports: $Exports<'primereact/card'>;
}
declare module 'primereact/chart.js' {
  declare module.exports: $Exports<'primereact/chart'>;
}
declare module 'primereact/checkbox.js' {
  declare module.exports: $Exports<'primereact/checkbox'>;
}
declare module 'primereact/chips.js' {
  declare module.exports: $Exports<'primereact/chips'>;
}
declare module 'primereact/colorpicker.js' {
  declare module.exports: $Exports<'primereact/colorpicker'>;
}
declare module 'primereact/column.js' {
  declare module.exports: $Exports<'primereact/column'>;
}
declare module 'primereact/columngroup.js' {
  declare module.exports: $Exports<'primereact/columngroup'>;
}
declare module 'primereact/components/accordion/Accordion.js' {
  declare module.exports: $Exports<'primereact/components/accordion/Accordion'>;
}
declare module 'primereact/components/autocomplete/AutoComplete.js' {
  declare module.exports: $Exports<'primereact/components/autocomplete/AutoComplete'>;
}
declare module 'primereact/components/autocomplete/AutoCompletePanel.js' {
  declare module.exports: $Exports<'primereact/components/autocomplete/AutoCompletePanel'>;
}
declare module 'primereact/components/breadcrumb/BreadCrumb.js' {
  declare module.exports: $Exports<'primereact/components/breadcrumb/BreadCrumb'>;
}
declare module 'primereact/components/button/Button.js' {
  declare module.exports: $Exports<'primereact/components/button/Button'>;
}
declare module 'primereact/components/calendar/Calendar.js' {
  declare module.exports: $Exports<'primereact/components/calendar/Calendar'>;
}
declare module 'primereact/components/calendar/CalendarPanel.js' {
  declare module.exports: $Exports<'primereact/components/calendar/CalendarPanel'>;
}
declare module 'primereact/components/captcha/Captcha.js' {
  declare module.exports: $Exports<'primereact/components/captcha/Captcha'>;
}
declare module 'primereact/components/card/Card.js' {
  declare module.exports: $Exports<'primereact/components/card/Card'>;
}
declare module 'primereact/components/chart/Chart.js' {
  declare module.exports: $Exports<'primereact/components/chart/Chart'>;
}
declare module 'primereact/components/checkbox/Checkbox.js' {
  declare module.exports: $Exports<'primereact/components/checkbox/Checkbox'>;
}
declare module 'primereact/components/chips/Chips.js' {
  declare module.exports: $Exports<'primereact/components/chips/Chips'>;
}
declare module 'primereact/components/colorpicker/ColorPicker.js' {
  declare module.exports: $Exports<'primereact/components/colorpicker/ColorPicker'>;
}
declare module 'primereact/components/colorpicker/ColorPickerPanel.js' {
  declare module.exports: $Exports<'primereact/components/colorpicker/ColorPickerPanel'>;
}
declare module 'primereact/components/column/Column.js' {
  declare module.exports: $Exports<'primereact/components/column/Column'>;
}
declare module 'primereact/components/columngroup/ColumnGroup.js' {
  declare module.exports: $Exports<'primereact/components/columngroup/ColumnGroup'>;
}
declare module 'primereact/components/contextmenu/ContextMenu.js' {
  declare module.exports: $Exports<'primereact/components/contextmenu/ContextMenu'>;
}
declare module 'primereact/components/datascroller/DataScroller.js' {
  declare module.exports: $Exports<'primereact/components/datascroller/DataScroller'>;
}
declare module 'primereact/components/datatable/BodyCell.js' {
  declare module.exports: $Exports<'primereact/components/datatable/BodyCell'>;
}
declare module 'primereact/components/datatable/BodyRow.js' {
  declare module.exports: $Exports<'primereact/components/datatable/BodyRow'>;
}
declare module 'primereact/components/datatable/DataTable.js' {
  declare module.exports: $Exports<'primereact/components/datatable/DataTable'>;
}
declare module 'primereact/components/datatable/FooterCell.js' {
  declare module.exports: $Exports<'primereact/components/datatable/FooterCell'>;
}
declare module 'primereact/components/datatable/HeaderCell.js' {
  declare module.exports: $Exports<'primereact/components/datatable/HeaderCell'>;
}
declare module 'primereact/components/datatable/RowCheckbox.js' {
  declare module.exports: $Exports<'primereact/components/datatable/RowCheckbox'>;
}
declare module 'primereact/components/datatable/RowRadioButton.js' {
  declare module.exports: $Exports<'primereact/components/datatable/RowRadioButton'>;
}
declare module 'primereact/components/datatable/ScrollableView.js' {
  declare module.exports: $Exports<'primereact/components/datatable/ScrollableView'>;
}
declare module 'primereact/components/datatable/TableBody.js' {
  declare module.exports: $Exports<'primereact/components/datatable/TableBody'>;
}
declare module 'primereact/components/datatable/TableFooter.js' {
  declare module.exports: $Exports<'primereact/components/datatable/TableFooter'>;
}
declare module 'primereact/components/datatable/TableHeader.js' {
  declare module.exports: $Exports<'primereact/components/datatable/TableHeader'>;
}
declare module 'primereact/components/dataview/DataView.js' {
  declare module.exports: $Exports<'primereact/components/dataview/DataView'>;
}
declare module 'primereact/components/deferredcontent/DeferredContent.js' {
  declare module.exports: $Exports<'primereact/components/deferredcontent/DeferredContent'>;
}
declare module 'primereact/components/dialog/Dialog.js' {
  declare module.exports: $Exports<'primereact/components/dialog/Dialog'>;
}
declare module 'primereact/components/dropdown/Dropdown.js' {
  declare module.exports: $Exports<'primereact/components/dropdown/Dropdown'>;
}
declare module 'primereact/components/dropdown/DropdownItem.js' {
  declare module.exports: $Exports<'primereact/components/dropdown/DropdownItem'>;
}
declare module 'primereact/components/dropdown/DropdownPanel.js' {
  declare module.exports: $Exports<'primereact/components/dropdown/DropdownPanel'>;
}
declare module 'primereact/components/editor/Editor.js' {
  declare module.exports: $Exports<'primereact/components/editor/Editor'>;
}
declare module 'primereact/components/fieldset/Fieldset.js' {
  declare module.exports: $Exports<'primereact/components/fieldset/Fieldset'>;
}
declare module 'primereact/components/fileupload/FileUpload.js' {
  declare module.exports: $Exports<'primereact/components/fileupload/FileUpload'>;
}
declare module 'primereact/components/fullcalendar/FullCalendar.js' {
  declare module.exports: $Exports<'primereact/components/fullcalendar/FullCalendar'>;
}
declare module 'primereact/components/gmap/GMap.js' {
  declare module.exports: $Exports<'primereact/components/gmap/GMap'>;
}
declare module 'primereact/components/growl/Growl.js' {
  declare module.exports: $Exports<'primereact/components/growl/Growl'>;
}
declare module 'primereact/components/growl/GrowlMessage.js' {
  declare module.exports: $Exports<'primereact/components/growl/GrowlMessage'>;
}
declare module 'primereact/components/inplace/Inplace.js' {
  declare module.exports: $Exports<'primereact/components/inplace/Inplace'>;
}
declare module 'primereact/components/inputmask/InputMask.js' {
  declare module.exports: $Exports<'primereact/components/inputmask/InputMask'>;
}
declare module 'primereact/components/inputswitch/InputSwitch.js' {
  declare module.exports: $Exports<'primereact/components/inputswitch/InputSwitch'>;
}
declare module 'primereact/components/inputtext/InputText.js' {
  declare module.exports: $Exports<'primereact/components/inputtext/InputText'>;
}
declare module 'primereact/components/inputtextarea/InputTextarea.js' {
  declare module.exports: $Exports<'primereact/components/inputtextarea/InputTextarea'>;
}
declare module 'primereact/components/keyfilter/KeyFilter.js' {
  declare module.exports: $Exports<'primereact/components/keyfilter/KeyFilter'>;
}
declare module 'primereact/components/lightbox/Lightbox.js' {
  declare module.exports: $Exports<'primereact/components/lightbox/Lightbox'>;
}
declare module 'primereact/components/listbox/ListBox.js' {
  declare module.exports: $Exports<'primereact/components/listbox/ListBox'>;
}
declare module 'primereact/components/listbox/ListBoxHeader.js' {
  declare module.exports: $Exports<'primereact/components/listbox/ListBoxHeader'>;
}
declare module 'primereact/components/listbox/ListBoxItem.js' {
  declare module.exports: $Exports<'primereact/components/listbox/ListBoxItem'>;
}
declare module 'primereact/components/megamenu/MegaMenu.js' {
  declare module.exports: $Exports<'primereact/components/megamenu/MegaMenu'>;
}
declare module 'primereact/components/menu/Menu.js' {
  declare module.exports: $Exports<'primereact/components/menu/Menu'>;
}
declare module 'primereact/components/menubar/Menubar.js' {
  declare module.exports: $Exports<'primereact/components/menubar/Menubar'>;
}
declare module 'primereact/components/menubar/MenubarSub.js' {
  declare module.exports: $Exports<'primereact/components/menubar/MenubarSub'>;
}
declare module 'primereact/components/message/Message.js' {
  declare module.exports: $Exports<'primereact/components/message/Message'>;
}
declare module 'primereact/components/messages/Messages.js' {
  declare module.exports: $Exports<'primereact/components/messages/Messages'>;
}
declare module 'primereact/components/messages/UIMessage.js' {
  declare module.exports: $Exports<'primereact/components/messages/UIMessage'>;
}
declare module 'primereact/components/multiselect/MultiSelect.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelect'>;
}
declare module 'primereact/components/multiselect/MultiSelectHeader.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelectHeader'>;
}
declare module 'primereact/components/multiselect/MultiSelectItem.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelectItem'>;
}
declare module 'primereact/components/multiselect/MultiSelectPanel.js' {
  declare module.exports: $Exports<'primereact/components/multiselect/MultiSelectPanel'>;
}
declare module 'primereact/components/orderlist/OrderList.js' {
  declare module.exports: $Exports<'primereact/components/orderlist/OrderList'>;
}
declare module 'primereact/components/orderlist/OrderListControls.js' {
  declare module.exports: $Exports<'primereact/components/orderlist/OrderListControls'>;
}
declare module 'primereact/components/orderlist/OrderListSubList.js' {
  declare module.exports: $Exports<'primereact/components/orderlist/OrderListSubList'>;
}
declare module 'primereact/components/organizationchart/OrganizationChart.js' {
  declare module.exports: $Exports<'primereact/components/organizationchart/OrganizationChart'>;
}
declare module 'primereact/components/overlaypanel/OverlayPanel.js' {
  declare module.exports: $Exports<'primereact/components/overlaypanel/OverlayPanel'>;
}
declare module 'primereact/components/paginator/CurrentPageReport.js' {
  declare module.exports: $Exports<'primereact/components/paginator/CurrentPageReport'>;
}
declare module 'primereact/components/paginator/FirstPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/FirstPageLink'>;
}
declare module 'primereact/components/paginator/LastPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/LastPageLink'>;
}
declare module 'primereact/components/paginator/NextPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/NextPageLink'>;
}
declare module 'primereact/components/paginator/PageLinks.js' {
  declare module.exports: $Exports<'primereact/components/paginator/PageLinks'>;
}
declare module 'primereact/components/paginator/Paginator.js' {
  declare module.exports: $Exports<'primereact/components/paginator/Paginator'>;
}
declare module 'primereact/components/paginator/PrevPageLink.js' {
  declare module.exports: $Exports<'primereact/components/paginator/PrevPageLink'>;
}
declare module 'primereact/components/paginator/RowsPerPageDropdown.js' {
  declare module.exports: $Exports<'primereact/components/paginator/RowsPerPageDropdown'>;
}
declare module 'primereact/components/panel/Panel.js' {
  declare module.exports: $Exports<'primereact/components/panel/Panel'>;
}
declare module 'primereact/components/panelmenu/PanelMenu.js' {
  declare module.exports: $Exports<'primereact/components/panelmenu/PanelMenu'>;
}
declare module 'primereact/components/password/Password.js' {
  declare module.exports: $Exports<'primereact/components/password/Password'>;
}
declare module 'primereact/components/picklist/PickList.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickList'>;
}
declare module 'primereact/components/picklist/PickListControls.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListControls'>;
}
declare module 'primereact/components/picklist/PickListItem.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListItem'>;
}
declare module 'primereact/components/picklist/PickListSubList.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListSubList'>;
}
declare module 'primereact/components/picklist/PickListTransferControls.js' {
  declare module.exports: $Exports<'primereact/components/picklist/PickListTransferControls'>;
}
declare module 'primereact/components/progressbar/ProgressBar.js' {
  declare module.exports: $Exports<'primereact/components/progressbar/ProgressBar'>;
}
declare module 'primereact/components/progressspinner/ProgressSpinner.js' {
  declare module.exports: $Exports<'primereact/components/progressspinner/ProgressSpinner'>;
}
declare module 'primereact/components/radiobutton/RadioButton.js' {
  declare module.exports: $Exports<'primereact/components/radiobutton/RadioButton'>;
}
declare module 'primereact/components/rating/Rating.js' {
  declare module.exports: $Exports<'primereact/components/rating/Rating'>;
}
declare module 'primereact/components/row/Row.js' {
  declare module.exports: $Exports<'primereact/components/row/Row'>;
}
declare module 'primereact/components/scrollpanel/ScrollPanel.js' {
  declare module.exports: $Exports<'primereact/components/scrollpanel/ScrollPanel'>;
}
declare module 'primereact/components/selectbutton/SelectButton.js' {
  declare module.exports: $Exports<'primereact/components/selectbutton/SelectButton'>;
}
declare module 'primereact/components/selectbutton/SelectButtonItem.js' {
  declare module.exports: $Exports<'primereact/components/selectbutton/SelectButtonItem'>;
}
declare module 'primereact/components/sidebar/Sidebar.js' {
  declare module.exports: $Exports<'primereact/components/sidebar/Sidebar'>;
}
declare module 'primereact/components/slidemenu/SlideMenu.js' {
  declare module.exports: $Exports<'primereact/components/slidemenu/SlideMenu'>;
}
declare module 'primereact/components/slider/Slider.js' {
  declare module.exports: $Exports<'primereact/components/slider/Slider'>;
}
declare module 'primereact/components/spinner/Spinner.js' {
  declare module.exports: $Exports<'primereact/components/spinner/Spinner'>;
}
declare module 'primereact/components/splitbutton/SplitButton.js' {
  declare module.exports: $Exports<'primereact/components/splitbutton/SplitButton'>;
}
declare module 'primereact/components/splitbutton/SplitButtonItem.js' {
  declare module.exports: $Exports<'primereact/components/splitbutton/SplitButtonItem'>;
}
declare module 'primereact/components/splitbutton/SplitButtonPanel.js' {
  declare module.exports: $Exports<'primereact/components/splitbutton/SplitButtonPanel'>;
}
declare module 'primereact/components/steps/Steps.js' {
  declare module.exports: $Exports<'primereact/components/steps/Steps'>;
}
declare module 'primereact/components/tabmenu/TabMenu.js' {
  declare module.exports: $Exports<'primereact/components/tabmenu/TabMenu'>;
}
declare module 'primereact/components/tabview/TabView.js' {
  declare module.exports: $Exports<'primereact/components/tabview/TabView'>;
}
declare module 'primereact/components/tieredmenu/TieredMenu.js' {
  declare module.exports: $Exports<'primereact/components/tieredmenu/TieredMenu'>;
}
declare module 'primereact/components/tieredmenu/TieredMenuSub.js' {
  declare module.exports: $Exports<'primereact/components/tieredmenu/TieredMenuSub'>;
}
declare module 'primereact/components/togglebutton/ToggleButton.js' {
  declare module.exports: $Exports<'primereact/components/togglebutton/ToggleButton'>;
}
declare module 'primereact/components/toolbar/Toolbar.js' {
  declare module.exports: $Exports<'primereact/components/toolbar/Toolbar'>;
}
declare module 'primereact/components/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'primereact/components/tooltip/Tooltip'>;
}
declare module 'primereact/components/tree/Tree.js' {
  declare module.exports: $Exports<'primereact/components/tree/Tree'>;
}
declare module 'primereact/components/tree/UITreeNode.js' {
  declare module.exports: $Exports<'primereact/components/tree/UITreeNode'>;
}
declare module 'primereact/components/treetable/TreeTable.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTable'>;
}
declare module 'primereact/components/treetable/TreeTableBody.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableBody'>;
}
declare module 'primereact/components/treetable/TreeTableBodyCell.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableBodyCell'>;
}
declare module 'primereact/components/treetable/TreeTableFooter.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableFooter'>;
}
declare module 'primereact/components/treetable/TreeTableHeader.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableHeader'>;
}
declare module 'primereact/components/treetable/TreeTableNode.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableNode'>;
}
declare module 'primereact/components/treetable/TreeTableRow.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableRow'>;
}
declare module 'primereact/components/treetable/TreeTableScrollableView.js' {
  declare module.exports: $Exports<'primereact/components/treetable/TreeTableScrollableView'>;
}
declare module 'primereact/components/tristatecheckbox/TriStateCheckbox.js' {
  declare module.exports: $Exports<'primereact/components/tristatecheckbox/TriStateCheckbox'>;
}
declare module 'primereact/components/utils/DomHandler.js' {
  declare module.exports: $Exports<'primereact/components/utils/DomHandler'>;
}
declare module 'primereact/components/utils/ObjectUtils.js' {
  declare module.exports: $Exports<'primereact/components/utils/ObjectUtils'>;
}
declare module 'primereact/components/utils/UniqueComponentId.js' {
  declare module.exports: $Exports<'primereact/components/utils/UniqueComponentId'>;
}
declare module 'primereact/contextmenu.js' {
  declare module.exports: $Exports<'primereact/contextmenu'>;
}
declare module 'primereact/datascroller.js' {
  declare module.exports: $Exports<'primereact/datascroller'>;
}
declare module 'primereact/datatable.js' {
  declare module.exports: $Exports<'primereact/datatable'>;
}
declare module 'primereact/dataview.js' {
  declare module.exports: $Exports<'primereact/dataview'>;
}
declare module 'primereact/deferredcontent.js' {
  declare module.exports: $Exports<'primereact/deferredcontent'>;
}
declare module 'primereact/dialog.js' {
  declare module.exports: $Exports<'primereact/dialog'>;
}
declare module 'primereact/dropdown.js' {
  declare module.exports: $Exports<'primereact/dropdown'>;
}
declare module 'primereact/editor.js' {
  declare module.exports: $Exports<'primereact/editor'>;
}
declare module 'primereact/fieldset.js' {
  declare module.exports: $Exports<'primereact/fieldset'>;
}
declare module 'primereact/fileupload.js' {
  declare module.exports: $Exports<'primereact/fileupload'>;
}
declare module 'primereact/fullcalendar.js' {
  declare module.exports: $Exports<'primereact/fullcalendar'>;
}
declare module 'primereact/gmap.js' {
  declare module.exports: $Exports<'primereact/gmap'>;
}
declare module 'primereact/growl.js' {
  declare module.exports: $Exports<'primereact/growl'>;
}
declare module 'primereact/inputmask.js' {
  declare module.exports: $Exports<'primereact/inputmask'>;
}
declare module 'primereact/inputswitch.js' {
  declare module.exports: $Exports<'primereact/inputswitch'>;
}
declare module 'primereact/inputtext.js' {
  declare module.exports: $Exports<'primereact/inputtext'>;
}
declare module 'primereact/inputtextarea.js' {
  declare module.exports: $Exports<'primereact/inputtextarea'>;
}
declare module 'primereact/lightbox.js' {
  declare module.exports: $Exports<'primereact/lightbox'>;
}
declare module 'primereact/listbox.js' {
  declare module.exports: $Exports<'primereact/listbox'>;
}
declare module 'primereact/megamenu.js' {
  declare module.exports: $Exports<'primereact/megamenu'>;
}
declare module 'primereact/menu.js' {
  declare module.exports: $Exports<'primereact/menu'>;
}
declare module 'primereact/menubar.js' {
  declare module.exports: $Exports<'primereact/menubar'>;
}
declare module 'primereact/message.js' {
  declare module.exports: $Exports<'primereact/message'>;
}
declare module 'primereact/messages.js' {
  declare module.exports: $Exports<'primereact/messages'>;
}
declare module 'primereact/multiselect.js' {
  declare module.exports: $Exports<'primereact/multiselect'>;
}
declare module 'primereact/orderlist.js' {
  declare module.exports: $Exports<'primereact/orderlist'>;
}
declare module 'primereact/organizationchart.js' {
  declare module.exports: $Exports<'primereact/organizationchart'>;
}
declare module 'primereact/overlaypanel.js' {
  declare module.exports: $Exports<'primereact/overlaypanel'>;
}
declare module 'primereact/paginator.js' {
  declare module.exports: $Exports<'primereact/paginator'>;
}
declare module 'primereact/panel.js' {
  declare module.exports: $Exports<'primereact/panel'>;
}
declare module 'primereact/panelmenu.js' {
  declare module.exports: $Exports<'primereact/panelmenu'>;
}
declare module 'primereact/password.js' {
  declare module.exports: $Exports<'primereact/password'>;
}
declare module 'primereact/picklist.js' {
  declare module.exports: $Exports<'primereact/picklist'>;
}
declare module 'primereact/progressbar.js' {
  declare module.exports: $Exports<'primereact/progressbar'>;
}
declare module 'primereact/progressspinner.js' {
  declare module.exports: $Exports<'primereact/progressspinner'>;
}
declare module 'primereact/radiobutton.js' {
  declare module.exports: $Exports<'primereact/radiobutton'>;
}
declare module 'primereact/rating.js' {
  declare module.exports: $Exports<'primereact/rating'>;
}
declare module 'primereact/row.js' {
  declare module.exports: $Exports<'primereact/row'>;
}
declare module 'primereact/scrollpanel.js' {
  declare module.exports: $Exports<'primereact/scrollpanel'>;
}
declare module 'primereact/selectbutton.js' {
  declare module.exports: $Exports<'primereact/selectbutton'>;
}
declare module 'primereact/sidebar.js' {
  declare module.exports: $Exports<'primereact/sidebar'>;
}
declare module 'primereact/slidemenu.js' {
  declare module.exports: $Exports<'primereact/slidemenu'>;
}
declare module 'primereact/slider.js' {
  declare module.exports: $Exports<'primereact/slider'>;
}
declare module 'primereact/spinner.js' {
  declare module.exports: $Exports<'primereact/spinner'>;
}
declare module 'primereact/splitbutton.js' {
  declare module.exports: $Exports<'primereact/splitbutton'>;
}
declare module 'primereact/steps.js' {
  declare module.exports: $Exports<'primereact/steps'>;
}
declare module 'primereact/tabmenu.js' {
  declare module.exports: $Exports<'primereact/tabmenu'>;
}
declare module 'primereact/tabview.js' {
  declare module.exports: $Exports<'primereact/tabview'>;
}
declare module 'primereact/tieredmenu.js' {
  declare module.exports: $Exports<'primereact/tieredmenu'>;
}
declare module 'primereact/togglebutton.js' {
  declare module.exports: $Exports<'primereact/togglebutton'>;
}
declare module 'primereact/toolbar.js' {
  declare module.exports: $Exports<'primereact/toolbar'>;
}
declare module 'primereact/tooltip.js' {
  declare module.exports: $Exports<'primereact/tooltip'>;
}
declare module 'primereact/tree.js' {
  declare module.exports: $Exports<'primereact/tree'>;
}
declare module 'primereact/treetable.js' {
  declare module.exports: $Exports<'primereact/treetable'>;
}
declare module 'primereact/tristatecheckbox.js' {
  declare module.exports: $Exports<'primereact/tristatecheckbox'>;
}
