// flow-typed signature: 26060f8f9285a80fb178f65d8f49d36d
// flow-typed version: <<STUB>>/primeicons_v1.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primeicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primeicons' {
  declare module.exports: any;
}
