// flow-typed signature: d197ad36244bb44087161c7aee73a9bf
// flow-typed version: <<STUB>>/random-id_v0.0.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-id/randomID' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-id/randomID.js' {
  declare module.exports: $Exports<'random-id/randomID'>;
}
