// flow-typed signature: 2ccbad1f582b59996204af4ced45f928
// flow-typed version: <<STUB>>/react-to-print_v2.0.0-alpha-6/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-to-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-to-print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-to-print/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-to-print/lib/index.js' {
  declare module.exports: $Exports<'react-to-print/lib/index'>;
}
