// flow-typed signature: 0f209ad041d14dcfa80ac8df92aeecea
// flow-typed version: <<STUB>>/react-confirm_v^0.1.18/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-confirm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-confirm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-confirm/lib/confirmable' {
  declare module.exports: any;
}

declare module 'react-confirm/lib/createConfirmation' {
  declare module.exports: any;
}

declare module 'react-confirm/lib/index' {
  declare module.exports: any;
}

declare module 'react-confirm/src/confirmable' {
  declare module.exports: any;
}

declare module 'react-confirm/src/createConfirmation' {
  declare module.exports: any;
}

declare module 'react-confirm/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-confirm/lib/confirmable.js' {
  declare module.exports: $Exports<'react-confirm/lib/confirmable'>;
}
declare module 'react-confirm/lib/createConfirmation.js' {
  declare module.exports: $Exports<'react-confirm/lib/createConfirmation'>;
}
declare module 'react-confirm/lib/index.js' {
  declare module.exports: $Exports<'react-confirm/lib/index'>;
}
declare module 'react-confirm/src/confirmable.js' {
  declare module.exports: $Exports<'react-confirm/src/confirmable'>;
}
declare module 'react-confirm/src/createConfirmation.js' {
  declare module.exports: $Exports<'react-confirm/src/createConfirmation'>;
}
declare module 'react-confirm/src/index.js' {
  declare module.exports: $Exports<'react-confirm/src/index'>;
}
