// flow-typed signature: 6f09e6b79055921d665f5cf3f41ceaf2
// flow-typed version: <<STUB>>/read-excel-file_v^2.0.5/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-excel-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-excel-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'read-excel-file/browser.default' {
  declare module.exports: any;
}

declare module 'read-excel-file/bundle/read-excel-file.min' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/convertToJson' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/parseDate' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/readXlsx' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/readXlsxFileBrowser' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/readXlsxFileContents' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/readXlsxFileNode' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/types/Email' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/types/Integer' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/types/URL' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/unpackXlsxFileBrowser' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/unpackXlsxFileNode' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/xmlBrowser' {
  declare module.exports: any;
}

declare module 'read-excel-file/commonjs/xmlNode' {
  declare module.exports: any;
}

declare module 'read-excel-file/index.commonjs' {
  declare module.exports: any;
}

declare module 'read-excel-file/json' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/convertToJson' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/parseDate' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/readXlsx' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/readXlsxFileBrowser' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/readXlsxFileContents' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/readXlsxFileNode' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/types/Email' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/types/Integer' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/types/URL' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/unpackXlsxFileBrowser' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/unpackXlsxFileNode' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/xmlBrowser' {
  declare module.exports: any;
}

declare module 'read-excel-file/modules/xmlNode' {
  declare module.exports: any;
}

declare module 'read-excel-file/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'read-excel-file/browser.default.js' {
  declare module.exports: $Exports<'read-excel-file/browser.default'>;
}
declare module 'read-excel-file/bundle/read-excel-file.min.js' {
  declare module.exports: $Exports<'read-excel-file/bundle/read-excel-file.min'>;
}
declare module 'read-excel-file/commonjs/convertToJson.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/convertToJson'>;
}
declare module 'read-excel-file/commonjs/parseDate.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/parseDate'>;
}
declare module 'read-excel-file/commonjs/readXlsx.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/readXlsx'>;
}
declare module 'read-excel-file/commonjs/readXlsxFileBrowser.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/readXlsxFileBrowser'>;
}
declare module 'read-excel-file/commonjs/readXlsxFileContents.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/readXlsxFileContents'>;
}
declare module 'read-excel-file/commonjs/readXlsxFileNode.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/readXlsxFileNode'>;
}
declare module 'read-excel-file/commonjs/types/Email.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/types/Email'>;
}
declare module 'read-excel-file/commonjs/types/Integer.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/types/Integer'>;
}
declare module 'read-excel-file/commonjs/types/URL.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/types/URL'>;
}
declare module 'read-excel-file/commonjs/unpackXlsxFileBrowser.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/unpackXlsxFileBrowser'>;
}
declare module 'read-excel-file/commonjs/unpackXlsxFileNode.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/unpackXlsxFileNode'>;
}
declare module 'read-excel-file/commonjs/xmlBrowser.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/xmlBrowser'>;
}
declare module 'read-excel-file/commonjs/xmlNode.js' {
  declare module.exports: $Exports<'read-excel-file/commonjs/xmlNode'>;
}
declare module 'read-excel-file/index.commonjs.js' {
  declare module.exports: $Exports<'read-excel-file/index.commonjs'>;
}
declare module 'read-excel-file/index' {
  declare module.exports: $Exports<'read-excel-file'>;
}
declare module 'read-excel-file/index.js' {
  declare module.exports: $Exports<'read-excel-file'>;
}
declare module 'read-excel-file/json.js' {
  declare module.exports: $Exports<'read-excel-file/json'>;
}
declare module 'read-excel-file/modules/convertToJson.js' {
  declare module.exports: $Exports<'read-excel-file/modules/convertToJson'>;
}
declare module 'read-excel-file/modules/parseDate.js' {
  declare module.exports: $Exports<'read-excel-file/modules/parseDate'>;
}
declare module 'read-excel-file/modules/readXlsx.js' {
  declare module.exports: $Exports<'read-excel-file/modules/readXlsx'>;
}
declare module 'read-excel-file/modules/readXlsxFileBrowser.js' {
  declare module.exports: $Exports<'read-excel-file/modules/readXlsxFileBrowser'>;
}
declare module 'read-excel-file/modules/readXlsxFileContents.js' {
  declare module.exports: $Exports<'read-excel-file/modules/readXlsxFileContents'>;
}
declare module 'read-excel-file/modules/readXlsxFileNode.js' {
  declare module.exports: $Exports<'read-excel-file/modules/readXlsxFileNode'>;
}
declare module 'read-excel-file/modules/types/Email.js' {
  declare module.exports: $Exports<'read-excel-file/modules/types/Email'>;
}
declare module 'read-excel-file/modules/types/Integer.js' {
  declare module.exports: $Exports<'read-excel-file/modules/types/Integer'>;
}
declare module 'read-excel-file/modules/types/URL.js' {
  declare module.exports: $Exports<'read-excel-file/modules/types/URL'>;
}
declare module 'read-excel-file/modules/unpackXlsxFileBrowser.js' {
  declare module.exports: $Exports<'read-excel-file/modules/unpackXlsxFileBrowser'>;
}
declare module 'read-excel-file/modules/unpackXlsxFileNode.js' {
  declare module.exports: $Exports<'read-excel-file/modules/unpackXlsxFileNode'>;
}
declare module 'read-excel-file/modules/xmlBrowser.js' {
  declare module.exports: $Exports<'read-excel-file/modules/xmlBrowser'>;
}
declare module 'read-excel-file/modules/xmlNode.js' {
  declare module.exports: $Exports<'read-excel-file/modules/xmlNode'>;
}
declare module 'read-excel-file/node.js' {
  declare module.exports: $Exports<'read-excel-file/node'>;
}
