// flow-typed signature: d7e827402542a0c4d1577725956b15cc
// flow-typed version: <<STUB>>/single-spa_v^4.0.3/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'single-spa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'single-spa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'single-spa/karma-saucelabs.conf' {
  declare module.exports: any;
}

declare module 'single-spa/karma.conf' {
  declare module.exports: any;
}

declare module 'single-spa/lib/single-spa' {
  declare module.exports: any;
}

declare module 'single-spa/src/applications/app-errors' {
  declare module.exports: any;
}

declare module 'single-spa/src/applications/app.helpers' {
  declare module.exports: any;
}

declare module 'single-spa/src/applications/apps' {
  declare module.exports: any;
}

declare module 'single-spa/src/applications/timeouts' {
  declare module.exports: any;
}

declare module 'single-spa/src/devtools/devtools' {
  declare module.exports: any;
}

declare module 'single-spa/src/jquery-support' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/bootstrap' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/lifecycle.helpers' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/load' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/mount' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/prop.helpers' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/unload' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/unmount' {
  declare module.exports: any;
}

declare module 'single-spa/src/lifecycles/update' {
  declare module.exports: any;
}

declare module 'single-spa/src/navigation/navigation-events' {
  declare module.exports: any;
}

declare module 'single-spa/src/navigation/reroute' {
  declare module.exports: any;
}

declare module 'single-spa/src/parcels/mount-parcel' {
  declare module.exports: any;
}

declare module 'single-spa/src/single-spa' {
  declare module.exports: any;
}

declare module 'single-spa/src/start' {
  declare module.exports: any;
}

declare module 'single-spa/src/utils/find' {
  declare module.exports: any;
}

declare module 'single-spa/webpack.config.analyze' {
  declare module.exports: any;
}

declare module 'single-spa/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'single-spa/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'single-spa/karma-saucelabs.conf.js' {
  declare module.exports: $Exports<'single-spa/karma-saucelabs.conf'>;
}
declare module 'single-spa/karma.conf.js' {
  declare module.exports: $Exports<'single-spa/karma.conf'>;
}
declare module 'single-spa/lib/single-spa.js' {
  declare module.exports: $Exports<'single-spa/lib/single-spa'>;
}
declare module 'single-spa/src/applications/app-errors.js' {
  declare module.exports: $Exports<'single-spa/src/applications/app-errors'>;
}
declare module 'single-spa/src/applications/app.helpers.js' {
  declare module.exports: $Exports<'single-spa/src/applications/app.helpers'>;
}
declare module 'single-spa/src/applications/apps.js' {
  declare module.exports: $Exports<'single-spa/src/applications/apps'>;
}
declare module 'single-spa/src/applications/timeouts.js' {
  declare module.exports: $Exports<'single-spa/src/applications/timeouts'>;
}
declare module 'single-spa/src/devtools/devtools.js' {
  declare module.exports: $Exports<'single-spa/src/devtools/devtools'>;
}
declare module 'single-spa/src/jquery-support.js' {
  declare module.exports: $Exports<'single-spa/src/jquery-support'>;
}
declare module 'single-spa/src/lifecycles/bootstrap.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/bootstrap'>;
}
declare module 'single-spa/src/lifecycles/lifecycle.helpers.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/lifecycle.helpers'>;
}
declare module 'single-spa/src/lifecycles/load.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/load'>;
}
declare module 'single-spa/src/lifecycles/mount.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/mount'>;
}
declare module 'single-spa/src/lifecycles/prop.helpers.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/prop.helpers'>;
}
declare module 'single-spa/src/lifecycles/unload.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/unload'>;
}
declare module 'single-spa/src/lifecycles/unmount.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/unmount'>;
}
declare module 'single-spa/src/lifecycles/update.js' {
  declare module.exports: $Exports<'single-spa/src/lifecycles/update'>;
}
declare module 'single-spa/src/navigation/navigation-events.js' {
  declare module.exports: $Exports<'single-spa/src/navigation/navigation-events'>;
}
declare module 'single-spa/src/navigation/reroute.js' {
  declare module.exports: $Exports<'single-spa/src/navigation/reroute'>;
}
declare module 'single-spa/src/parcels/mount-parcel.js' {
  declare module.exports: $Exports<'single-spa/src/parcels/mount-parcel'>;
}
declare module 'single-spa/src/single-spa.js' {
  declare module.exports: $Exports<'single-spa/src/single-spa'>;
}
declare module 'single-spa/src/start.js' {
  declare module.exports: $Exports<'single-spa/src/start'>;
}
declare module 'single-spa/src/utils/find.js' {
  declare module.exports: $Exports<'single-spa/src/utils/find'>;
}
declare module 'single-spa/webpack.config.analyze.js' {
  declare module.exports: $Exports<'single-spa/webpack.config.analyze'>;
}
declare module 'single-spa/webpack.config.dev.js' {
  declare module.exports: $Exports<'single-spa/webpack.config.dev'>;
}
declare module 'single-spa/webpack.config.js' {
  declare module.exports: $Exports<'single-spa/webpack.config'>;
}
