// flow-typed signature: 859e61b0503987aada2355a6834a3a5b
// flow-typed version: <<STUB>>/single-spa-react_v^2.9.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'single-spa-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'single-spa-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'single-spa-react/lib/single-spa-react' {
  declare module.exports: any;
}

declare module 'single-spa-react/parcel/index' {
  declare module.exports: any;
}

declare module 'single-spa-react/src/parcel' {
  declare module.exports: any;
}

declare module 'single-spa-react/src/parcel.proptypes' {
  declare module.exports: any;
}

declare module 'single-spa-react/src/parcel.test' {
  declare module.exports: any;
}

declare module 'single-spa-react/src/single-spa-react' {
  declare module.exports: any;
}

declare module 'single-spa-react/src/single-spa-react.test' {
  declare module.exports: any;
}

declare module 'single-spa-react/src/test-setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'single-spa-react/lib/single-spa-react.js' {
  declare module.exports: $Exports<'single-spa-react/lib/single-spa-react'>;
}
declare module 'single-spa-react/parcel/index.js' {
  declare module.exports: $Exports<'single-spa-react/parcel/index'>;
}
declare module 'single-spa-react/src/parcel.js' {
  declare module.exports: $Exports<'single-spa-react/src/parcel'>;
}
declare module 'single-spa-react/src/parcel.proptypes.js' {
  declare module.exports: $Exports<'single-spa-react/src/parcel.proptypes'>;
}
declare module 'single-spa-react/src/parcel.test.js' {
  declare module.exports: $Exports<'single-spa-react/src/parcel.test'>;
}
declare module 'single-spa-react/src/single-spa-react.js' {
  declare module.exports: $Exports<'single-spa-react/src/single-spa-react'>;
}
declare module 'single-spa-react/src/single-spa-react.test.js' {
  declare module.exports: $Exports<'single-spa-react/src/single-spa-react.test'>;
}
declare module 'single-spa-react/src/test-setup.js' {
  declare module.exports: $Exports<'single-spa-react/src/test-setup'>;
}
