// flow-typed signature: 0a75a31164e480f7b6537548c5cf7709
// flow-typed version: <<STUB>>/tailwindcss_v^0.7.4/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwindcss/defaultConfig' {
  declare module.exports: any;
}

declare module 'tailwindcss/defaultConfig.stub' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/build' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/build' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/help' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/index' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/commands/init' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/constants' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/emoji' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/main' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/cli/utils' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/appearance' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/backgroundAttachment' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/backgroundColors' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/backgroundPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/backgroundRepeat' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/backgroundSize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/borderCollapse' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/borderColors' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/borderRadius' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/borderStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/borderWidths' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/cursor' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/display' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/flexbox' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/float' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/fonts' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/fontWeights' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/height' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/leading' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/lists' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/margin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/maxHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/maxWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/minHeight' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/minWidth' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/negativeMargin' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/objectFit' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/objectPosition' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/opacity' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/outline' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/overflow' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/padding' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/pointerEvents' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/position' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/resize' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/shadows' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/svgFill' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/svgStroke' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/tableLayout' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/textAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/textColors' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/textSizes' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/textStyle' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/tracking' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/userSelect' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/verticalAlign' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/visibility' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/whitespace' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/width' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/generators/zIndex' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/index' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/registerConfigAsDependency' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteClassApplyAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteResponsiveAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteScreenAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteTailwindAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/lib/substituteVariantsAtRules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/plugins/container' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/processTailwindFeatures' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/buildMediaQuery' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/buildSelectorVariant' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/cloneNodes' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/collapseWhitespace' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/defineClass' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/defineClasses' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/escapeClassName' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/focusable' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/generateModules' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/generateUtilities' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/generateVariantFunction' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/hoverable' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/mergeConfigWithDefaults' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/parseObjectStyles' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/prefixSelector' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/prefixTree' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/processPlugins' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/responsive' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/util/wrapWithVariants' {
  declare module.exports: any;
}

declare module 'tailwindcss/lib/utilityModules' {
  declare module.exports: any;
}

declare module 'tailwindcss/plugins/container' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tailwindcss/defaultConfig.js' {
  declare module.exports: $Exports<'tailwindcss/defaultConfig'>;
}
declare module 'tailwindcss/defaultConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/defaultConfig.stub'>;
}
declare module 'tailwindcss/lib/build.js' {
  declare module.exports: $Exports<'tailwindcss/lib/build'>;
}
declare module 'tailwindcss/lib/cli.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli'>;
}
declare module 'tailwindcss/lib/cli/commands/build.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/build'>;
}
declare module 'tailwindcss/lib/cli/commands/help.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/help'>;
}
declare module 'tailwindcss/lib/cli/commands/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/index'>;
}
declare module 'tailwindcss/lib/cli/commands/init.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/commands/init'>;
}
declare module 'tailwindcss/lib/cli/constants.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/constants'>;
}
declare module 'tailwindcss/lib/cli/emoji.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/emoji'>;
}
declare module 'tailwindcss/lib/cli/main.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/main'>;
}
declare module 'tailwindcss/lib/cli/utils.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli/utils'>;
}
declare module 'tailwindcss/lib/generators/appearance.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/appearance'>;
}
declare module 'tailwindcss/lib/generators/backgroundAttachment.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/backgroundAttachment'>;
}
declare module 'tailwindcss/lib/generators/backgroundColors.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/backgroundColors'>;
}
declare module 'tailwindcss/lib/generators/backgroundPosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/backgroundPosition'>;
}
declare module 'tailwindcss/lib/generators/backgroundRepeat.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/backgroundRepeat'>;
}
declare module 'tailwindcss/lib/generators/backgroundSize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/backgroundSize'>;
}
declare module 'tailwindcss/lib/generators/borderCollapse.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/borderCollapse'>;
}
declare module 'tailwindcss/lib/generators/borderColors.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/borderColors'>;
}
declare module 'tailwindcss/lib/generators/borderRadius.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/borderRadius'>;
}
declare module 'tailwindcss/lib/generators/borderStyle.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/borderStyle'>;
}
declare module 'tailwindcss/lib/generators/borderWidths.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/borderWidths'>;
}
declare module 'tailwindcss/lib/generators/cursor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/cursor'>;
}
declare module 'tailwindcss/lib/generators/display.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/display'>;
}
declare module 'tailwindcss/lib/generators/flexbox.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/flexbox'>;
}
declare module 'tailwindcss/lib/generators/float.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/float'>;
}
declare module 'tailwindcss/lib/generators/fonts.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/fonts'>;
}
declare module 'tailwindcss/lib/generators/fontWeights.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/fontWeights'>;
}
declare module 'tailwindcss/lib/generators/height.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/height'>;
}
declare module 'tailwindcss/lib/generators/leading.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/leading'>;
}
declare module 'tailwindcss/lib/generators/lists.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/lists'>;
}
declare module 'tailwindcss/lib/generators/margin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/margin'>;
}
declare module 'tailwindcss/lib/generators/maxHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/maxHeight'>;
}
declare module 'tailwindcss/lib/generators/maxWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/maxWidth'>;
}
declare module 'tailwindcss/lib/generators/minHeight.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/minHeight'>;
}
declare module 'tailwindcss/lib/generators/minWidth.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/minWidth'>;
}
declare module 'tailwindcss/lib/generators/negativeMargin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/negativeMargin'>;
}
declare module 'tailwindcss/lib/generators/objectFit.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/objectFit'>;
}
declare module 'tailwindcss/lib/generators/objectPosition.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/objectPosition'>;
}
declare module 'tailwindcss/lib/generators/opacity.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/opacity'>;
}
declare module 'tailwindcss/lib/generators/outline.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/outline'>;
}
declare module 'tailwindcss/lib/generators/overflow.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/overflow'>;
}
declare module 'tailwindcss/lib/generators/padding.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/padding'>;
}
declare module 'tailwindcss/lib/generators/pointerEvents.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/pointerEvents'>;
}
declare module 'tailwindcss/lib/generators/position.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/position'>;
}
declare module 'tailwindcss/lib/generators/resize.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/resize'>;
}
declare module 'tailwindcss/lib/generators/shadows.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/shadows'>;
}
declare module 'tailwindcss/lib/generators/svgFill.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/svgFill'>;
}
declare module 'tailwindcss/lib/generators/svgStroke.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/svgStroke'>;
}
declare module 'tailwindcss/lib/generators/tableLayout.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/tableLayout'>;
}
declare module 'tailwindcss/lib/generators/textAlign.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/textAlign'>;
}
declare module 'tailwindcss/lib/generators/textColors.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/textColors'>;
}
declare module 'tailwindcss/lib/generators/textSizes.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/textSizes'>;
}
declare module 'tailwindcss/lib/generators/textStyle.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/textStyle'>;
}
declare module 'tailwindcss/lib/generators/tracking.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/tracking'>;
}
declare module 'tailwindcss/lib/generators/userSelect.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/userSelect'>;
}
declare module 'tailwindcss/lib/generators/verticalAlign.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/verticalAlign'>;
}
declare module 'tailwindcss/lib/generators/visibility.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/visibility'>;
}
declare module 'tailwindcss/lib/generators/whitespace.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/whitespace'>;
}
declare module 'tailwindcss/lib/generators/width.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/width'>;
}
declare module 'tailwindcss/lib/generators/zIndex.js' {
  declare module.exports: $Exports<'tailwindcss/lib/generators/zIndex'>;
}
declare module 'tailwindcss/lib/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib/index'>;
}
declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/evaluateTailwindFunctions'>;
}
declare module 'tailwindcss/lib/lib/registerConfigAsDependency.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/registerConfigAsDependency'>;
}
declare module 'tailwindcss/lib/lib/substituteClassApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteClassApplyAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteResponsiveAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteResponsiveAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteScreenAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteScreenAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteTailwindAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteTailwindAtRules'>;
}
declare module 'tailwindcss/lib/lib/substituteVariantsAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteVariantsAtRules'>;
}
declare module 'tailwindcss/lib/plugins/container.js' {
  declare module.exports: $Exports<'tailwindcss/lib/plugins/container'>;
}
declare module 'tailwindcss/lib/processTailwindFeatures.js' {
  declare module.exports: $Exports<'tailwindcss/lib/processTailwindFeatures'>;
}
declare module 'tailwindcss/lib/util/buildMediaQuery.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/buildMediaQuery'>;
}
declare module 'tailwindcss/lib/util/buildSelectorVariant.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/buildSelectorVariant'>;
}
declare module 'tailwindcss/lib/util/cloneNodes.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/cloneNodes'>;
}
declare module 'tailwindcss/lib/util/collapseWhitespace.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/collapseWhitespace'>;
}
declare module 'tailwindcss/lib/util/defineClass.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/defineClass'>;
}
declare module 'tailwindcss/lib/util/defineClasses.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/defineClasses'>;
}
declare module 'tailwindcss/lib/util/escapeClassName.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/escapeClassName'>;
}
declare module 'tailwindcss/lib/util/focusable.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/focusable'>;
}
declare module 'tailwindcss/lib/util/generateModules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/generateModules'>;
}
declare module 'tailwindcss/lib/util/generateUtilities.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/generateUtilities'>;
}
declare module 'tailwindcss/lib/util/generateVariantFunction.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/generateVariantFunction'>;
}
declare module 'tailwindcss/lib/util/hoverable.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/hoverable'>;
}
declare module 'tailwindcss/lib/util/mergeConfigWithDefaults.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/mergeConfigWithDefaults'>;
}
declare module 'tailwindcss/lib/util/parseObjectStyles.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseObjectStyles'>;
}
declare module 'tailwindcss/lib/util/prefixSelector.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/prefixSelector'>;
}
declare module 'tailwindcss/lib/util/prefixTree.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/prefixTree'>;
}
declare module 'tailwindcss/lib/util/processPlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/processPlugins'>;
}
declare module 'tailwindcss/lib/util/responsive.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/responsive'>;
}
declare module 'tailwindcss/lib/util/wrapWithVariants.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/wrapWithVariants'>;
}
declare module 'tailwindcss/lib/utilityModules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/utilityModules'>;
}
declare module 'tailwindcss/plugins/container.js' {
  declare module.exports: $Exports<'tailwindcss/plugins/container'>;
}
