// @flow
import { I18n } from "aws-amplify";
import moment from "moment";
// $FlowIgnore: require moment
require("moment/locale/it");

export default class LocalizationStore {
  culture: string;
  constructor(culture: string) {
    this.culture = culture;
    I18n.putVocabularies(labels);
    I18n.setLanguage(culture);
    moment.locale(culture);
  }

  get = (id: string) => {
    return I18n.get(id);
  };
}

const labels = {
  it: {
    veicoli: "Veicoli",
    clienti: "Clienti",
    gruppo: "Gruppo",
    vendite: "Vendite",
    gruppoVendite: "Gruppo vendite",
    gestioneDomini: "Gestione domini",
    importazioneDispositivi: "Importazione dispositivi",
    statoDispositivi: "Stato dispositivi",
    statoDispositivo: "Stato dispositivo",
    statoOrdine: "Stato ordine",
    messoSpedizione: "Messo in spedizione il",
    importazioneSim: "Importazione SIM",
    statoSimCards: "Stato SIM cards",
    associaDispositiviSim: "Associa dispositivi/SIM",
    codice: "Codice",
    documenti: "Documenti",
    testoCampagna: "Testo campagna",
    targa: "Targa",
    targaAssociata: "Targa associata",
    creatoDa: "Creato da",
    creaSpedizione: "Crea spedizione",
    elencoUtentiHeader:
      "Elenco utenti (in giallo gli utenti in attesa di conferma / cambio password)",
    elencoEntita: "Elenco entita",
    elencoOrdini: "Elenco ordini",
    nome: "Nome",
    cognome: "Cognome",
    nomeUtente: "Nome utente",
    elencoDealers: "Elenco dealers",
    visualizzaVenditeXVend: "Visualizza vendite per questo venditore",
    venditorePer: "Venditore per",
    venditeFatte: "Vendite fatte",
    visualizzaClienti: "Visualizza clienti",
    visualizzaVeicoli: "Visualizza veicoli",
    visualizzaOrdiniGruppo: "visualizza ordini del gruppo",
    visualizzaOrdini: "Visualizza ordini",
    venditore: "Venditore",
    visualizzaModelliTagliando: "Visualizza modelli tagliando",
    visualizzaRichiami: "Visualizza richiami",
    visualizzaVenditeGruppo: "Visualizza vendite del gruppo",
    visualizzaVendite: "Visualizza vendite",
    dettaglioGerarchia: "Dettaglio gerarchia",
    visualizzaMagazzino: "Visualizza magazzino",
    visualizzaMarketing: "Visualizza marketing",
    agenteRiferimento: "Agente di riferimento",
    riferimentoOrdine: "Riferimento ordine",
    denominazione: "Denominazione",
    kmPercorsiDa: "Km percorsi da",
    KmPercorsiA: "Km percorsi a",
    indirizzo: "Indirizzo",
    tipo: "Tipo",
    tipoDispositivo: "Tipo dispositivo",
    aggiungiAgente: "Aggiungi agente",
    aggiungiTagliando: "Aggiungi nuovo modello tagliando",
    aggiungiOrdine: "Aggiungi ordine",
    pec: "PEC",
    ruoli: "Ruoli",
    cellulare: "Cellulare",
    indirizzoCliente: "Indirizzo cliente",
    telefonoCliente: "Telefono cliente",
    mailCliente: "E-mail cliente",
    CfPiCliente: "C.fiscale/P.IVA Cliente",
    targheAssociateVendita: "Targhe associate alla vendita",
    modelloDeviceQuantita: "Modello device e quantita",
    quantitativoRichiesto: "Quantitativo richiesto",
    modelloDevice: "Modello device",
    effettuataDa: "Effettuata da",
    elencoModelliDealer: "Elenco modelli tagliando per il dealer selezionato",
    selezionaCliente: "Seleziona cliente",
    selezionaClientePrivato: "Seleziona cliente privato",
    aggiungiClientePrivato: "Aggiungi nuovo cliente privato",
    aggiungiClienteAzienda: "Aggiungi nuovo cliente azienda",
    limiteChilometri: "Limite chilometri",
    limiteMesi: "Limite mesi",
    modificaClienteSelezionato: "Modifica cliente selezionato",
    modificaDealer: "Modifica dealer",
    modificaDispositivoSelezionato: "Modifica dispositivo selezionato",
    modificaOrdine: "Modifica ordine",
    intestatoA: "Intestato a",
    aggiungiFiliale: "Aggiungi filiale",
    aggiungiVenditore: "Aggiungi venditore",
    modificaVenditore: "Modifica venditore",
    dispositiviEvidenziatiVerde: "Dispositivi disponibili evidenziati in verde",
    magazzinoDispositivi: "Magazzino dispositivi",
    modificaAgenteSelezionato: "Modifica agente selezionato",
    modificaAzienda: "Modifica cliente azienda",
    dealer: "Dealer",
    scadenzaKm: "Scadenza KM",
    scadenzaMesi: "Scadenza in mesi",
    giorniScadenza: "Giorni scadenza",
    elencoClienti: "Elenco clienti",
    elencoCollaudi: "Elenco collaudi",
    elencoVeicoli: "Elenco veicoli",
    dataRichiamo: "Data richiamo",
    dateEvento: "Data evento",
    dataCreazioneRichiamo: "Data creazione richiamo",
    codiceFatturazioneElettronica: "Codice Fatturazione Elettronica",
    dataAppuntamento: "Data appuntamento",
    kmScadenza: "KM alla scadenza",
    dataChiusura: "Data chiusura",
    noteChiusura: "Note chiusura",
    noteOrdine: "Note ordine",
    elencoVeicoliXDealer: "Elenco veicoli per il dealer selezionato",
    customizzaRichiamo: "Customizza il richiamo",
    completaRichiamo: "Completa richiamo",
    elencoCampagneMarketing:
      "Elenco campagne marketing per il dealer selezionato",
    creaCampagna: "Crea campagna",
    modificaVenditoreSelez: "Modifica venditore selezionato",
    nomeCampagna: "Nome campagna",
    nomeCompletoCliente: "Nome completo cliente",
    descrizione: "Descrizione",
    criteriRicerca: "Criteri di ricerca",
    possibiliVeicoliCoinvolti: "Possibili veicoli coinvolti",
    descrizioneRichiamo: "Descrizione richiamo",
    descrizioneCampagna: "Descrizione campagna",
    dataInizio: "Data inizio",
    dataFine: "Data fine",
    campagneMarketing: "Campagne marketing",
    veicoliCoinvolti: "Veicoli coinvolti",
    modificaCampagna: "Modifica campagna",
    dataCollaudo: "Data collaudo",
    dataConsegnaRichiesta: "Data consegna richiesta",
    dataCOnsegnaDesiderata: "Data consegna desiderata",
    consegnatoIl: "Consegnato il",
    ordini: "Ordini",
    gruppoOrdini: "Gruppo ordini",
    ordiniAgente: "Ordini agente",
    collaudi: "Collaudi",
    aggiungiNuovoDealer: "Aggiungi nuovo dealer",
    aggiungiNuovoVeicolo: "Aggiungi nuovo veicolo",
    dealers: "Dealers",
    agenti: "Agenti",
    appTitle: "Piramis manager Application",
    loginTitle: "Accedi a Piramis",
    modelloDispositivo: "Modello dispositivo",
    dispositiviRichiesti: "Dispositivi richiesti",
    modificaVeicolo: "Modifica veicolo",
    creaRichiamo: "Crea richiamo",
    evento: "Evento",
    login: "Login",
    yes: "SI",
    no: "NO",
    danger: "Danger!",
    dangerZone: "Danger zone",
    email: "E-mail",
    elencoAgenti: "Elenco agenti",
    roles: "Ruoli",
    enabled: "Attivo",
    creationDate: "Data creazione",
    dataUltimoAggiormanento: "Data ultimo aggiornamento",
    schedaOrdine: "Scheda ordine",
    createdDate: "Creato il",
    print: "Print",
    visualizzaDealersAssociati: "Visualizza dealers associati",
    visualizzaDettaglioOrdine: "Visualizza dettaglio ordine",
    new: "Nuovo",
    lastUpdated: "Modificato il",
    marketing: "Marketing",
    cancel: "Annulla",
    sezioneDisponibile1: "Sezione disponibile solo per utenti abilitati",
    abbinamentoSatSim: "Abbinamento SAT - SIM",
    richiestoDa: "Richiesto da",
    messagioAbbinaDispositivi:
      "Immetti il numero di dispositivi da abbinare. Scansiona prima tutti i seriali dei dispositivi e poi gli iccid delle sim.",
    delete: "Elimina",
    add: "Aggiungi",
    admin: "Amministrazione",
    resultsNumber: "Totale risultati: ",
    ristampaEtichetta: "ristampaEtichetta",
    totaleDispositivi: "Totale dispositivi",
    ragioneSociale: "Ragione sociale",
    tipoProdotto: "Tipo prodotto",
    password: "Password",
    confirm: "Conferma",
    error: "Errore",
    dashboard: "Dashboard",
    storage: "Magazzino",
    simCards: "SIM Cards",
    supplier: "Fornitore",
    model: "Modello",
    tagliandi: "Tagliandi",
    modelliTagliando: "Modelli tagliando",
    carrier: "Operatore",
    users: "Utenti",
    user: "Utente",
    simType: "Tipo SIM",
    datiVeicolo: "Dati veicolo",
    insertDate: "Data inserimento",
    datiUtente: "Dati utente",
    mieiCollaudi: "I miei collaudi",
    devices: "Dispositivi",
    available: "Disponibili",
    nuovoCollaudo: "Nuovo collaudo",
    nuovoTicket: "Nuovo ticket",
    lavoraTicket: "Lavora ticket",
    paired: "Abbinati",
    dateFormat: "dd/mm/yy",
    gridColDates: "DD MMMM YYYY HH:mm",
    importFile: "File import",
    massiveImport: "Importazione massiva",
    massiveImportSat: "Importazione massiva SAT",
    massiveImportSim: "Importazione massiva SIM",
    loginValidationMessage: "Username e password sono obbligatori",
    "User does not exist.": "Utente non trovato",
    "Incorrect username or password.": "Nome utente o password errati",
    verifyUser: "Conferma utente",
    verificationCode: "Codice di verifica",
    verifyCodeValidationMessage: "Inserire il codice di verifica",
    resendCode: "Spedisci un nuovo codice",
    forgotPassword: "Hai scordato la password?",
    emailMandatory: "Inserire la email",
    forgotPasswordTitle: "Resetta la password",
    reset: "Reset",
    submitPasswordTitle: "Crea nuova password",
    menuTheme: "Tema menu",
    menuType: "Tipo menu",
    devicesStatus: "Stato dispositivi",
    simStatus: "Stato sim cards",
    successImport: "Record importati con successo",
    failureImport: "Record in errore",
    chooseFile: "Scegli file",
    confirmAction: "Sicuro di voler proseguire?",
    save: "Salva",
    attenzione: "Attenzione",
    domainData: "Dati di dominio",
    insertionDate: "Data inserimento",
    status: "Stato",
    elencoRichiami: "Elenco richiami",
    elencoDispositivi: "Elenco dispositivi",
    verificaAbbinamentiConferma: "Verifica abbinamenti e conferma",
    numeroDispositiviAbbinare: "Numero di dispositivi da abbinare",
    scansionaCodiciPremiInvio: "Scansiona codice o immetti e premi invio",
    scansionaCodici: "Scansiona codici",
    stampaEtichette: "Stampa etichette",
    cliente: "Cliente",
    modificaSimSelezionata: "Modifica SIM selezioanta",
    codiceFiscale: "Codice fiscale",
    modificaDealerSelez: "Modifica dealer selezionato",
    ricomincia: "Ricomincia",
    codiceFiscaleIva: "Codice fiscale/P.IVA",
    azienda: "Azienda",
    privato: "Privato",
    partitaIva: "Partita IVA",
    dettaglioCliente: "Dettaglio cliente",
    tipoVeicolo: "Tipo veicolo",
    dataPrimaImmatricolazione: "Data prima immatricolazione",
    immatricolataDal: "Immatricolata dal",
    immatricolataAl: "Immatricolata al",
    province: "Provincia",
    dataChiusuraRichiamo: "Data chiusura richiamo",
    km: "KM",
    alimentazione: "Alimentazione",
    personaRiferimento: "Persona di riferimento",
    marca: "Marca",
    allestimento: "Allestimento",
    numeroTelaio: "Numero telaio",
    telaio: "Telaio",
    nrDispositivi: "Nr. Dispositivi",
    dispositivo: "Dispositivo",
    imei: "IMEI",
    tel: "Telefono",
    fornitore: "Fornitore",
    nrTel: "Numero tel",
    prodotto: "Prodotto",
    modello: "Modello",
    stato: "Stato",
    note: "Note",
    richiamaTraKm: "Richiama tra KM",
    richiamaTraMesi: "Richiama tra mesi",
    descrizioneProssimoRichiamo: "Descrizione prossimo richiamo",
    noteRichiamo: "Note richiamo",
    dataInserimento: "Data inserimento",
    presentDomainData: "Dati di dominio attuali (formato JSON)",
    sampleDomainData: "Esempio di JSON dei dati di dominio",
    serialNumber: "Seriale",
    areYousure: "Sei sicuro di voler proseguire?",
    UsernameExistsException: "Utente gia' esistente",
    importDomainData:
      "Inserire un file contenente il JSON per i domini piramis",
    importValidation:
      "Tutti i campi sono obbligatori. Il file di import deve essere di tipo xlsx",
    submitPasswordSubTitle:
      "Il codice di verifica dovrebbe esserti arrivato nella tua casella di posta. Verifica anche nello spam",
    apiCallError:
      "Errore durante l'esecuzione della richiesta. Si prega di riprovare",
    apiErrorTitle: "Errore!!",
    "Username/client id combination not found.": "utente non esistente",
    newPasswordRequest:
      "L'amministratore di sistema ha richiesto di cambiare la password",
    apiSuccessTitle: "Operazione completata!",
    successAction:
      "Azione eseguita con successo! le modifiche potrebbero non essere immediatamente visibili. In tal caso utilizza gli appositi pulsanti per il refresh",
    addUser: "Aggiungi utente",
    FORCE_CHANGE_PASSWORD: "Cambio password",
    CONFIRMED: "Confermato",
    changeUserRoles: "Modifica i ruoli utente",
    loadMoreUsers: "Carica altri utenti..",
    "User is disabled":
      "utente disabilitato: contattare gli amministratori di sistema",
    confirmDisableUser:
      "Se prosegui l'utente selezionato verra' disabilitato. Confermi?",
    confirmResetPassword:
      "Se prosegui la password dell'utente selezionato verra' resettata. confermi?",
    confirmEnableUser:
      "Se prosegui l'utente selezionato verra' abilitato. Confermi?",
    searchUser: "Ricerca utente",
    "An account with the given email already exists.":
      "Esiste gia' un utente con la mail inserita",
    ZERO_RESULTS: "Nessun indirizzo trovato",
    "phone is a required field": "il numero di telefono e' obbligatorio",
    missingSatSim: "Dispositivo e sim non trovati",
    missingSat: "Dispositivo non trovato",
    missingSim: "Sim non trovata",
    wrongSatSimStatus: "Dispositivo e sim in stato diverso da 'inserito'",
    wrongSatStatus: "Dispositivo gia' abbinato",
    wrongSimStatus: "Dim gia' abbinata",
    confirmDeleteUser:
      "Sicuro di voler proseguire? Confermando rimuoverai l'utenza in modo definitivo. Nel caso ci fossero dealers associati, gli stessi non potranno accedere ai loro dati. Considera l'opzione di disabilitare l'utenza"
  }
};
